sudo: required
services:
  - docker

before_install:
  - docker build -t trungnv184/docker-app -f Dockerfile.dev .

script:
  - docker run trungnv184/docker-app

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-571854268523"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: "$AWS_ACCESS_SECRET_KEY"
