services:
- docker

before_install:
- docker build -t trungnv184/docker-app -f Dockerfile.dev .

script:
- docker run trungnv184/docker-app npm run test --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-571854268523"
  bucket_path: "docker"
  on:
    branch: master
