# sudo: required
language: generic
services:
  - docker

# before_install:
#   - docker build -t trungnv184/docker-app -f Dockerfile.dev .

# script:
#   - docker run trungnv184/docker-app

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-app"
  env: "Dockerapp-env"
  bucket_name: "web-app-vn"
  bucket_path: "docker-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_ACCESS_SECRET_KEY
    
